export const AttachmentTypes = {
    EVENT: "EVENT",
    SUPERVISOR_APPROVAL: "SUPERVISOR_APPROVAL",
    DEPARTMENT_HEAD_APPROVAL: "DEPARTMENT_HEAD_APPROVAL",
    PROOF_OF_COMPLETION: "PROOF_OF_COMPLETION"
}